language: c
compiler:
  - gcc
install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc-multilib g++-multilib cmake
before_script:
  - cmake source/compiler -DCMAKE_C_FLAGS=-m32 -DCPACK_GENERATOR=TGZ
script:
  - make
  - make package
deploy:
  provider: releases
  api_key:
    secure: gDAuRNlF2uVhVHyZtJrX6MwNxnkfkQzohrC/6UcKAgqt+NKs4vZyq5FzTUceiDAkB0se70ZVx08e9ibAiXP/b7D1MPkAEiRxt9J6Vu3x6Bi1kPPuK5RfjFeT3gc1SbrULAP8Nz0NdU0chUhei6/V5NGhTegwp925DJOISq7+Ibw=
  file_glob: true
  file: 'pawnc-*-linux.tar.gz'
  skip_cleanup: true
  on:
    tags: true
    repo: Zeex/pawn
