version: '{build}'

configuration:
  - RelWithDebInfo

before_build:
  - cmake source/compiler

build_script:
  - cmake --build . --config %CONFIGURATION%

artifacts:
  - path: RelWithDebInfo/pawncc.exe
    name: Compiler executable

  - path: RelWithDebInfo/pawnc.dll
    name: Compiler library
