version: '{build}'

configuration:
  - RelWithDebInfo

before_build:
  - cmake -G "Visual Studio 10 2010" source/compiler

build_script:
  - cmake --build . --config %CONFIGURATION%

artifacts:
  - path: RelWithDebInfo/pawncc.exe
    name: Pawn compiler
  - path: RelWithDebInfo/pawncc.pdb
    name: Pawn compiler - debug info

  - path: RelWithDebInfo/pawnc.dll
    name: Pawn compiler library
  - path: RelWithDebInfo/pawnc.pdb
    name: Pawn compiler library - debug info

  - path: RelWithDebInfo/pawndisasm.exe
    name: Pawn disassembler
  - path: RelWithDebInfo/pawndisasm.pdb
    name: Pawn disassembler - debug info
