version: '{build}'

configuration:
  - RelWithDebInfo

before_build:
  - cmake -G "Visual Studio 10 2010" source/compiler

build_script:
  - cmake --build . --config %CONFIGURATION%

artifacts:
  - path: RelWithDebInfo/pawncc.exe
    name: Pawn compiler

  - path: RelWithDebInfo/pawnc.dll
    name: Pawn compiler library

  - path: RelWithDebInfo/pawndisasm.exe
    name: Pawn disassembler
